name: Sync Missing Translations

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  sync-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install polib

      - name: Sync Missing Translations
        run: |
          python <<EOF
          import polib

          # Завантаження файлів
          untranslated = polib.pofile('ukrainian.po')
          original = polib.pofile('strings.pot')

          # Створення мапи оригінальних записів з урахуванням msgctxt
          original_dict = {(entry.msgctxt, entry.msgid): entry for entry in original}

          # Синхронізація відсутніх перекладів
          for entry in untranslated:
              key = (entry.msgctxt, entry.msgid)  # Враховуємо контекст
              if not entry.msgstr and key in original_dict:
                  entry.msgstr = original_dict[key].msgstr

          # Збереження оновленого файлу
          untranslated.save('ukrainian.po')
          EOF

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Sync missing translations from strings.pot'
          file_pattern: 'ukrainian.po'
