name: XliffToPo

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'uk/**/temp.xliff'

permissions:
  contents: write

jobs:
  merge_translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python & install pip
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - run: |
          python -m pip install --upgrade pip
          echo "Python version: $(python --version)"

      - name: Convert xliff to po
        run: python .github/scripts/convert_translations.py

      - name: Check PO file
        run: test -s ukrainian.po || (echo "PO file is empty or missing" && exit 1)

      - name: Commit Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git rm uk/temp.xliff
          git add ukrainian.po
          git commit -m "Convert xliff to po" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}
